wip

diff --git a/.github/workflows/authorized-actors.yml b/.github/workflows/authorized-actors.yml
--- a/.github/workflows/authorized-actors.yml
+++ b/.github/workflows/authorized-actors.yml
@@ -14,7 +14,8 @@ jobs:
           whitelist: DWSR,renovate[bot],dependabot[bot]
           github_token: "${{ secrets.GITHUB_TOKEN }}"
       - name: User is unauthorized
-        if: "${{ ! steps.auth_check.outputs.authorized }}"
         run: |
-          echo '::error title=User Unauthorized::User ${{ github.actor }} is not authorized to run this workflow!'
-          exit 1
+          if [ '${{ ! steps.auth_check.outputs.authorized }}' != 'true' ]; then
+            echo '::error title=User Unauthorized::User ${{ github.actor }} is not authorized to run this workflow!'
+            exit 1
+          fi
